apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-sample
  namespace: kube-system
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-north-1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: swiss-army-kube-sub2zero #${local.cluster_name}
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: test-secrets
    creationPolicy: Owner
  data:
  - secretKey: cleanspeak_admin_pass
    remoteRef:
      key: swiss-army-kube-sub2zero #${local.cluster_name}